//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales
    {
        public int SaleId { get; set; }
        public Nullable<int> SaleProduct { get; set; }
        public Nullable<int> SaleCustomer { get; set; }
        public Nullable<byte> SaleEmployee { get; set; }
        public Nullable<decimal> SalePreis { get; set; }
        public Nullable<bool> SaleStatus { get; set; }
    
        public virtual Tbl_Customers Tbl_Customers { get; set; }
        public virtual Tbl_Employees Tbl_Employees { get; set; }
        public virtual Tbl_Products Tbl_Products { get; set; }
    }
}
